### ISSUE TITLE
java.lang.IllegalArgumentException: 0 is not a valid line for a file

### ISSUE THREAD

**Issue by jonmelia** [sbaudoin/sonar-ansible#15]
Hi,

ansible-lint 4.1.0
Sonarqube 7.1.0.11001
sonar-ansible: latest version

I am getting some java errors at the end of the sonar scan..

the Ansible linting appears to run fine all the way to the end and then I hit this issue..

11:37:15.282 DEBUG: Problems found: []
11:37:15.282 DEBUG: Saving issue: missing document end "..." (document-end)

[11:37:15] 11:37:15.288 INFO: ------------------------------------------------------------------------
11:37:15.288 INFO: EXECUTION FAILURE
11:37:15.288 INFO: ------------------------------------------------------------------------
11:37:15.288 INFO: Total time: 5:47.959s

[11:37:15] 11:37:15.405 INFO: Final Memory: 54M/864M
11:37:15.405 INFO: ------------------------------------------------------------------------

[11:37:15] 11:37:15.405 ERROR: Error during SonarQube Scanner execution

[11:37:15] java.lang.IllegalArgumentException: 0 is not a valid line for a file

[11:37:15] 	at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:308)

[11:37:15] 	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:246)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.selectLine(DefaultInputFile.java:269)
	at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.saveIssues(YamlSensor.java:172)
	at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.runChecks(YamlSensor.java:151)
	at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.execute(YamlSensor.java:103)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
[11:37:15] 
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:302)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:297)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:271)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)

[11:37:15] 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)

[11:37:15] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)

[11:37:15] 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

[11:37:15] Return code: 1.

**Comment by sbaudoin** [comment]
Hello,

You mentioned Jenkins and npm in the issue's title: does this mean that without Jenkins and/or npm everything's fine?

The message "java.lang.IllegalArgumentException: 0 is not a valid line for a file" suggests that the problem relates to a specific file. So can you identify a set of files with which you have the error and a set of files for which you don't? I need some more context information to be able to reproduce and understand the issue, in the best case you can provide me with an sample file that raises the issue.

**Comment by jonmelia** [comment]
I'll try and identify the file and come back to you.  I was scanning hundreds so it may take a little while.

**Comment by jonmelia** [comment]
OK, I've discovered the issue.  If you have any empty yml files in your Ansible roles with just a --- at the start and nothing else then it throws the above error.  I have removed all the blank files and it now works.  It may be useful to just skip these files for scanning or not throw an error..

**Comment by jonmelia** [comment]
This appears unrelated to Jenkins and npm...

**Comment by sbaudoin** [comment]
Indeed. Having such a file is not part of my test cases. I'll fix it soon.

**Comment by dacofr** [comment]
Hello, 
I've got the same problem with ansible-lint 4.1.0 and file that only contains "---"
I've add a CR to my file to solve the problem.

Thanks

**Comment by sbaudoin** [comment]
Hello,

Thanks for the detail. It took some times but I eventually managed to find the culprit: the rule DocumenEndCheck ("For correct parsing especially in the case of multiple or embedded documents, documents should end with a document end marker") of the YAML plugin. So I have filed the issue sbaudoin/sonar-yaml#27. I'll notify you as soon as a fix has been released.

**Comment by sbaudoin** [comment]
Hello,

Release [1.4.3 of the sonar-yaml plugin](https://github.com/sbaudoin/sonar-yaml/releases/tag/v1.4.3) has been released. Please use this version to fix the issue.
