### ISSUE TITLE
SonarQube analysis fails when ansible-lint binary doesn't exist

### ISSUE THREAD

**Issue by axel3rd** [sbaudoin/sonar-ansible#3]
When project contain some `.yml` file but `ansible-lint` is not available on host, the SonarQube analysis fails with:

```
INFO: Sensor Ansible Lint Sensor [ansible]
INFO: 0/0 source files have been analyzed
ERROR: Error executing command
java.io.IOException: Cannot run program "ansible-lint": error=2, No such file or directory
INFO: Sensor Ansible Lint Sensor [ansible] (done) | time=11ms
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
INFO: Sensor JavaXmlSensor [java]
	at com.github.sbaudoin.sonar.plugins.ansible.rules.AbstractAnsibleSensor.executeCommand(AbstractAnsibleSensor.java:168)
INFO: Sensor JavaXmlSensor [java] (done) | time=1ms
	at com.github.sbaudoin.sonar.plugins.ansible.rules.AbstractAnsibleSensor.executeWithAnsibleLint(AbstractAnsibleSensor.java:112)
INFO: Sensor HTML [web]
	at com.github.sbaudoin.sonar.plugins.ansible.rules.AnsibleSensor.execute(AnsibleSensor.java:42)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
    [...]
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 35 common frames omitted
```

It could be better if SonarQube analysis would not be broken, and a log WARN or ERROR displayed with requirement about 'ansible-lint' binary (for better analysis, ...).

**Comment by sbaudoin** [comment]
From what I can see there is an ugly stack trace that could be removed. The actual problem is the `Thread.currentThread().interrupt()` executed whereas the actual exception is an `IOException`. I'm going to fix that.
